[package]
name = "impossible-inferences-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
impossible-inferences-domain.workspace = true
impossible-inferences-engine.workspace = true
impossible-inferences-protocol.workspace = true
impossible-server-core.workspace = true

[dev-dependencies]
impossible-server-testkit.workspace = true

[lints]
workspace = true
